version: "3.9"

services:
  app:
    image: ahmedromia/my-nest-app:latest   # build & push this first
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: kafeel
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  mysqldata:
