export enum education {
  ASSOCIATE = 'ASSOCIATE',
  BACHELOR = 'BACHELOR',
  MASTER = 'MASTER',
  DOCTORATE = 'DOCTORATE',
  DIPLOMA = 'DIPLOMA',
}
export enum languageLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDITE',
  NATIVE = 'NATIVE',
}
export enum FileType {
  CV = 'CV',
  IMAGE = 'IMAGE',
}
export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  FILE = 'FILE',
}

export const enum Code {
  PHONENUMBER_USED = 'PHONENUMBER_USED',
  UN_APPROVED = 'UN_APPROVED',
  license_must_valid_files = 'license_must_valid_files',
  INVALID_OTP = 'INVALID_OTP',
  NO_CHANGED_VALUES = 'NO_CHANGED_VALUES',
  DELETED = 'DELETED',
  WRONG_CREDS = 'WRONG_CREDS',
  CV_REQUIRED = 'CV_REQUIRED',
  UN_VERIFIED = 'UN_VERIFIED',
  UN_AUTORIZED = 'UN_AUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  BAD_INPUT = 'BAD_INPUT',
  SUCCESS = 'SUCCESS',
  WRONG_OLD_PASSWORD = 'WRONG_OLD_PASSWORD',
  WRONG_OTP = 'WRONG_OTP',
  MUST_BE_VIDEO_LESS_30MB = 'MUST_BE_VIDEO_LESS_30MB',
  USER_TYPE_REQUIRED = 'USER_TYPE_REQUIRED',
  SMTH_WITH_DB = 'SMTH_WITH_DB',
  TOO_BIG_FILE = 'TOO_BIG_FILE',
  EMAIL_USED = 'EMAIL_USED',
}

export enum skillLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDITE',
  PROFISSIONAL = 'PROFISSIONAL',
}
export const enum tokenType {
  EXPIRED = 'EXPIRED',
  VALID = 'VALID',
  NOTVALID = 'NOTVALID',
}
export const enum MailResponses {
  VERIFY_EMAIL = 'to verify your email',
  RESET_PASSWORD = 'to reset your password',
  FORGET_PASSWORD = 'to change your Password',
}

export const enum mailSubjects {
  VERIFY_EMAIL = 'Verify Email',
  RESET_PASSWORD = 'Reset Password',
  FORGET_PASSWORD = 'Forget Password',
}
export enum PERMISSION {
  IS_PHONE_VERIFIED = 'IS_PHONE_VERIFIED',
  IS_EMAIL_VERIFIED = 'IS_EMAIL_VERIFIED',
  IS_APPROVED = 'IS_APPROVED',
}

export const enum valuesString {
  PRESENT = 'PRESENT',
  UPDATED = 'UPDATED',
}
export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  TEMPORARY = 'TEMPORARY',
  INTERNSHIP = 'INTERNSHIP',
}
export enum UserType {
  WORKER = 'WORKER',
  KAFEEL = 'KAFEEL',
  COMPANY = 'COMPANY',
  ADMIN = 'ADMIN',
}

export enum PreferredSponsorType {
  COMPANY = 'COMPANY',
  INDIVIDUAL = 'INDIVIDUAL',
  GOVERNMENT = 'GOVERNMENT',
}
export const enum ValidationErrors {
  MUST_BE_SPONSORTYPE = 'MUST_BE_SPONSORTYPE',
  MUST_JOB_TYPE = 'MUST_JOB_TYPE',
  MUST_URL = 'MUST_URL',
  NO_SPACE_NO_SPECIAL_CHRACHTER = 'NO_SPACE_NO_SPECIAL_CHRACHTER',
  INVALID_LANGUAGE_LEVEL = 'INVALID_LANGUAGE_LEVEL',
  INVALID_SKILL_LEVEL = 'INVALID_SKILL_LEVEL',
  INVALID_EDUCATION_ENUM = 'INVALID_EDUCATION_ENUM',
  INVALID_DATE = 'INVALID_DATE',
  MUST_BE_VALID_USERTYPE = 'MUST_BE_VALID_USERTYPE',
  MUST_UNIQUE = 'MUST_UNIQUE',
  REQUIRED = 'REQUIRED',
  MUST_EMAIL = 'MUST_EMAIL',
  MUST_8_CHRACHTERS = 'MUST_8_CHRACHTERS',
  MUST_NUMBER = 'MUST_NUMBER',
  MUST_STRING = 'MUST_STRING',
  NUMBER_OUT_OF_RANGE = 'NUMBER_OUT_OF_RANGE',
  STRING_OUT_OF_RANGE = 'STRING_OUT_OF_RANGE',
  MUST_VALID_POSITION = 'MUST_VALID_POSITION',
  MUST_VALID_FOOT = 'MUST_VALID_FOOT',
  MUST_VALID_GENDER = 'MUST_VALID_GENDER',
  UNVALID_PHONE_NUMBER = 'UNVALID_PHONE_NUMBER',
  UNVALID_USER_TYPE = 'UNVALID_USER_TYPE',
  MUST_VALID_SKILLLEVEL = 'MUST_VALID_SKILLLEVEL',
  MUST_VALID_WORKING_HOURS = 'MUST_VALID_WORKING_HOURS',
  UNVALID_SPACE = 'UNVALID_SPACE',
  IMAGE_OVERSIZE = 'IMAGE_OVERSIZE',
  PDF_OVERSIZE = 'PDF_OVERSIZE',
  MUST_PDF = 'MUST_PDF',
  MUST_IMAGE = 'MUST_IMAGE',
}
export enum PostedJobDate {
  'pastMonth' = 30,
  'pastWeek' = 7,
  'past24Hours' = 0,
}
export const baseUrl ="https://kafeel.eventoapp.info"